DATA:
  IMG_SIZE: 224
TRAIN:
  USE_CHECKPOINT: false
MODEL:
  SWIN:
    APE: false
    DEPTHS: [2, 2, 6, 2]
    EMBED_DIM: 96
    IN_CHANS: 3
    MLP_RATIO: 4.0
    NUM_HEADS: [3, 6, 12, 24]
    PATCH_NORM: true
    PATCH_SIZE: 4
    QKV_BIAS: true
    QK_SCALE: null
    WINDOW_SIZE: 7
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  NUM_CLASSES: 1000
